Don't crash if ini specified bsas are not present: RRR
Could be traced back as far as 6aec0ce6f29a5dfb71b7f856143b439cf00be8d6.

Traceback (most recent call last):
  File "bash\bash.py", line 524, in main
  File "bash\bash.py", line 692, in _main
  File "bash\basher\__init__.py", line 4172, in Init
  File "bash\bosh\__init__.py", line 3437, in init_stores
  File "bash\bosh\__init__.py", line 2103, in __init__
  File "bash\bosh\__init__.py", line 1597, in __init__
  File "bash\bosh\__init__.py", line 2124, in refresh
  File "bash\bosh\__init__.py", line 2032, in _modinfos_cache_wrapper
  File "bash\bosh\__init__.py", line 2317, in _refresh_mod_inis_and_strings
  File "bash\game\__init__.py", line 687, in get_bsas_from_inis
  File "bash\bolt.py", line 715, in __delitem__
KeyError: FName('Skyrim - Voices.bsa')

The report is on shiny brand new 313 and reportedly 312.1 works - see
also faed98042aa74c511b474820c856468aab40447f - this is an edge case,
there are others in this code (see comments in get_bsas_from_inis) -
at some point (bsa tab) we should revisit.

__init__.py  685 get_bsas_from_inis: BSA Skyrim - Voices.bsa not found in FNDict({FName('Dawnguard.bsa'): BSAInfo<Dawnguard.bsa>, FName('Dragonborn.bsa'): BSAInfo<Dragonborn.bsa>, FName('HearthFires.bsa'): BSAInfo<HearthFires.bsa>, FName('HighResTexturePack01.bsa'): BSAInfo<HighResTexturePack01.bsa>, FName('HighResTexturePack02.bsa'): BSAInfo<HighResTexturePack02.bsa>, FName('HighResTexturePack03.bsa'): BSAInfo<HighResTexturePack03.bsa>, FName('Update.bsa'): BSAInfo<Update.bsa>, FName('AMatterOfTime.bsa'): BSAInfo<AMatterOfTime.bsa>, FName('Extended UI.bsa'): BSAInfo<Extended UI.bsa>, FName('Footprints.bsa'): BSAInfo<Footprints.bsa>, FName('JaxonzSmartLooter.bsa'): BSAInfo<JaxonzSmartLooter.bsa>, FName('MinimalHUD.bsa'): BSAInfo<MinimalHUD.bsa>, FName('QuickStart3_NoHelmet.bsa'): BSAInfo<QuickStart3_NoHelmet.bsa>, FName('SkyUI.bsa'): BSAInfo<SkyUI.bsa>, FName('StalhrimSourceFix.bsa'): BSAInfo<StalhrimSourceFix.bsa>, FName('UIExtensions.bsa'): BSAInfo<UIExtensions.bsa>, FName('Unofficial Skyrim Legendary Edition Patch.bsa'): BSAInfo<Unofficial Skyrim Legendary Edition Patch.bsa>})
__init__.py  685 get_bsas_from_inis: BSA Skyrim - VoicesExtra.bsa not found in FNDict({FName('Dawnguard.bsa'): BSAInfo<Dawnguard.bsa>, FName('Dragonborn.bsa'): BSAInfo<Dragonborn.bsa>, FName('HearthFires.bsa'): BSAInfo<HearthFires.bsa>, FName('HighResTexturePack01.bsa'): BSAInfo<HighResTexturePack01.bsa>, FName('HighResTexturePack02.bsa'): BSAInfo<HighResTexturePack02.bsa>, FName('HighResTexturePack03.bsa'): BSAInfo<HighResTexturePack03.bsa>, FName('Update.bsa'): BSAInfo<Update.bsa>, FName('AMatterOfTime.bsa'): BSAInfo<AMatterOfTime.bsa>, FName('Extended UI.bsa'): BSAInfo<Extended UI.bsa>, FName('Footprints.bsa'): BSAInfo<Footprints.bsa>, FName('JaxonzSmartLooter.bsa'): BSAInfo<JaxonzSmartLooter.bsa>, FName('MinimalHUD.bsa'): BSAInfo<MinimalHUD.bsa>, FName('QuickStart3_NoHelmet.bsa'): BSAInfo<QuickStart3_NoHelmet.bsa>, FName('SkyUI.bsa'): BSAInfo<SkyUI.bsa>, FName('StalhrimSourceFix.bsa'): BSAInfo<StalhrimSourceFix.bsa>, FName('UIExtensions.bsa'): BSAInfo<UIExtensions.bsa>, FName('Unofficial Skyrim Legendary Edition Patch.bsa'): BSAInfo<Unofficial Skyrim Legendary Edition Patch.bsa>})

But the bsas are present (needs-info) - so what is happening? One thing
that might happen is that the bsas are loaded via a previous key and
therefore removed from available bsas. Still not sure about the
relative order of inis/bsas inside a key - still WIP so for instance
anything would be better than those two dictionaries, even assigning
bsa_lo/bsa_cause attributes to the basinf - we would need to revisit
for full bsa tab anyway - # 233.